### ISSUE TITLE
clone下来修改api和url就报错ModuleNotFoundError: No module named 'tools.infer

### ISSUE THREAD

**Issue by pilipala00622** [lazyFrogLOL/llmdocparser#3]
Traceback (most recent call last):
  File "/llmdocparser/llmdocparser/llm_parser.py", line 4, in <module>
    from llmdocparser.parser.layout_parser import parse_pdf_to_images
  File "/.venv/lib/python3.10/site-packages/llmdocparser/parser/layout_parser.py", line 4, in <module>
    from paddleocr.ppstructure.recovery.recovery_to_doc import sorted_layout_boxes
  File "/.venv/lib/python3.10/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/.venv/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 34, in <module>
    from tools.infer import predict_system
ModuleNotFoundError: No module named 'tools.infer'

**Comment by lazyFrogLOL** [comment]
> Traceback (most recent call last): File "/llmdocparser/llmdocparser/llm_parser.py", line 4, in from llmdocparser.parser.layout_parser import parse_pdf_to_images File "/.venv/lib/python3.10/site-packages/llmdocparser/parser/layout_parser.py", line 4, in from paddleocr.ppstructure.recovery.recovery_to_doc import sorted_layout_boxes File "/.venv/lib/python3.10/site-packages/paddleocr/**init**.py", line 14, in from .paddleocr import * File "/.venv/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 34, in from tools.infer import predict_system ModuleNotFoundError: No module named 'tools.infer'

   This project uses Poetry for dependency management. Make sure you have Poetry installed. If not, you can follow the instructions in the [Poetry Installation Guide](https://python-poetry.org/docs/#installation).

   Once Poetry is installed, run the following command in the project's root directory to install the dependencies:

   ```bash
   poetry install
   ```

   This will read the `pyproject.toml` file and install all the required dependencies for the project.
